version: '3.8'
services:
  api:
    build: ./be
    container_name: api_backend
    ports:
      - '6060:6060'
    volumes:
      - ./api:/app
      - ./app/node_modules
  client:
    build: ./fe
    container_name: client_frontend
    ports:
      - '4040:4040'
    volumes:
      - ./client:/app
      - ./app/node_modules
    stdin_open: true
    tty: true